NAME: "DifyAgent"
VERSION: "v0.0.1"
# 暴露给前端的参数选项以及默认值
PARAMETERS: [
  {
    NAME: "DIFY_API_URL",
    DEFAULT: ""
  },
  {
    NAME: "DIFY_API_KEY",
    DEFAULT: ""
  },
  {
    NAME: "AGENT_TTS",
    DEFAULT: "DifyAPI"
  }
]