COMMON:
  NAME: "Awesome-Digital-Human"
  VERSION: "v0.0.1"
  LOG_LEVEL: "DEBUG"
SERVER:
  IP: "0.0.0.0"
  PORT: 8000
  ENGINES:
    ASR: 
      SUPPORT_LIST: [ "difyAPI.yaml" ]
      DEFAULT: "difyAPI.yaml"
    LLM: 
      SUPPORT_LIST: [ ]
      DEFAULT: ""
    TTS: 
      SUPPORT_LIST: [ "difyAPI.yaml" ]
      DEFAULT: "difyAPI.yaml"
  AGENTS: 
    SUPPORT_LIST: [ "difyAgent.yaml" ]
    DEFAULT: "difyAgent.yaml"